I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 344, in script
    "Tienes un correo de: [Redacted]"
KeyError: u'Redacted'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 344, in script
    "Tienes un correo de: [Redacted]"
  File "C:\Users\brite\Downloads\renpy-7.4.11-sdk/renpy/ast.py", line 721, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\brite\Downloads\renpy-7.4.11-sdk/renpy/exports.py", line 1419, in say
    who(what, *args, **kwargs)
  File "C:\Users\brite\Downloads\renpy-7.4.11-sdk/renpy/character.py", line 1236, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "C:\Users\brite\Downloads\renpy-7.4.11-sdk/renpy/character.py", line 1155, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "C:\Users\brite\Downloads\renpy-7.4.11-sdk/renpy/character.py", line 1135, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Users\brite\Downloads\renpy-7.4.11-sdk/renpy/substitutions.py", line 270, in substitute
    s = formatter.vformat(s, (), kwargs)
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 563, in vformat
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 585, in _vformat
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 646, in get_field
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 605, in get_value
KeyError: u'Redacted'

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Dreamed Interrogatory 1.0
Sun Dec 26 03:36:34 2021
